#!/bin/bash


time python fit_full.py norm_kpi_2011_$1 1 2>&1 | tee log.norm_kpi_2011_$1.txt
time python fit_full.py norm_kpi_2011_unblinded_$1 1 2>&1 | tee log.norm_kpi_2011_unblinded_$1.txt
time python fit_full.py norm_kpi_2012_$1 1 2>&1 | tee log.norm_kpi_2012_$1.txt



